apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: uykc8n9l2-nodejs
  janus-idp.io/tekton: uykc8n9l2-nodejs
  backstage.io/kubernetes-id: uykc8n9l2-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: uykc8n9l2-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
